sudo: required
language: ruby
rvm:
- 2.0.0
bundler_args: --without production
addons:
  postgresql: '9.3'
services:
- postgresql
- docker
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- rake
after_script:
- docker build --tag social-app:0.1 .
- docker tag social-app:0.1 carmelocuenca/social-app:0.1
- docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push carmelocuenca/social-app:0.1
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    # travis encrypt varialble=$variable
    # DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_EMAIL
    - secure: "NsRFf0AAevZaPeF1RKRL33Wsc61S8DNaoT3OEEHM5zwMIji4jruMwR4nW4uYLrSiBo7JyYTHus6utbbZrYilhnWr0+GpF3OMdPwGUIJbpOnEC6XqiYOKhnHOoLdY/+s7bXCJ+AXWjrEdWsG5MZnmZ+O6jBXj2v1bdhpv0sXA/TEoOMHEWdL8Rp3p53iT99QXTtqEmRxkWmsHWR6u+a9ml4kJ9G4n5CHQpU+Obt/I7ZETgeSVpsCI+YcBhPwUTERs+QGXxMgJQQmcdHdPZ+SsQf0coLVfB5htxZefsla3BSFpbv0gAuR6cawuoYs97ZuJKmPYd6uC9Kc5sfeKFZcWTyB672HTgtA6v3cT4iBchkPIk87SicQ/WM7f6nhIRlpai/lzJK+SOVfeS17dJW/v9wMNglrqTvNJzoZNSWI9tfE3zA0JMyRLOAiuxPN23ybM4yY1NnmqdOkBkuVPExVPt2T/hbF1py6dxK7EgKaOUDwd8RNdjR57EGmkL7aI4VbSQKqPvYKWdJSYnQN18itzwj09hRbQ1StyVwauNtFGpFA5qpnfa+gRK4YpOyiudk0fwwe4kEvfBVyr7Uoy4o+NDlCAG1JLFmMfV+ZUIcSifTgQq7qC1cPbo4eP2DjF97mvq7VhI/zqv9NyKA9gwPlwxckLEVueIeU4oYlOGqFcYhk="
    - secure: "HVHgm4U0WHL0lUf5kluW2zfqlGUYSFIn5lQquIKu8XKX0XjrgO0E36MAl0RCy1LpiBf//Ve3POL2yp/ooa/oFPueM6mveWm9/VXj297JXcEd1grjdpHsoPf/iXfmyUdEDjL2Ob3gOYrlCpwC2WgIloX3YKvK6ZXgSM9ya1pBYVk02QVA7ebHUoJtowyWaTS9tOo87wOyrDyMTaAMOB6Vk1bOD4VA6dGSs04rnPrZaDCuP/QwXgTTAjQJocV5/9/U4M758djlkcpfQsee+Wkf0n8kImF/AGaOpAgBvwS30SyFigEqmftkZmaqkDml7/ONkYnY9aNk9xErVHEemZaN8cSEr8nzUdO7g99YV5Hi+BFmYUGVx6pNCsSjTtZz5RM/UWhQ0nZtW/965Ustd3SBQ4KflWP/pIN3UgT5zeffmXbWlgOlOghXOg8Itjj5iIWTo2q9cgB/5JwM4YJ4tp+Pctnl12ilkIZAp9vWCO9AI2z3LsXNsciQ67gA5EolC1qMVqXpp6iXDXAWAo8Ir5mm3Qs4nE/hRY6VS0D7nsH5HCEPL0RWBvjF3mqwbpuQw7zjipqS39CEFJ6urnErDRoSKzOlS+yHYcfxT+VzHshelYpBf7YpnQRbNSR9O1vjdNgdhflsj4j5/toqHgU9ZTrvXehj232Ab/0m+ppsv8jGYMU="
    - secure: "ZFe6IRDOdZN/n6ggYuukVLYNv3G+0AP2kpxnHjEU5FK/lSf7WfwTU7N1aFqcl9KfzYeBR+F8hNm0MVOgFIXHTmR/uG+N/HWWYph8nDWzTcLzufEgasGmFiTGd56UgXsbSq66fii85b8WjAbaVO8lHwR+79h7Ty151JDZ3zZLakeqfdy8ZcpYzf3k2La8DN+PwEYe5hgElKHrVGJQpRwD1KhlrM0i4AMrBFS/l4NyKaB4vbOWq20ipCX/da33+8vQvumKVJabR9LnxGOY8mY9FrdQBvs/2ozL+X6eChtLher1xYkpFeJkng4XYC5dS00/3m5DgeUDYRTYMBgmf018ZDH4gkuza8pzTwXufWSgaw+issht06dpGpes6QnhDgJI9DwRLjJcL/2VVxK1JyCx1KnyUJWC+n1KUl5Bxof5UKIubi7zE6k2bZVpZCacVjGpkB9tgvN4A8R/y2P7680PktfC8rpvhSuM8rX1REa8JKmRe8I/+4uRO/fZeQqhxfnQTHCEQhrNslQulSr8DuXWmNOSg4835gMA+d60oBkvogKeJJXDLrwxNzy5R+KiELP0RXnXcvFUvsqDA0qfVvwnIfOJLflT1JLX8SIE7vMUXgdCleOtpCVO1ZXrLkCBJ8+YGStbKPfV9EfChUmHOjCPegu5W18y7qR+RLSQEZgDh/g="
